#!/usr/bin/env bash
# Defensive rebase of gx/main onto a fresh xai-org/grok-build main snapshot.
#
# Strict-bash implementation of the runbook in docs/gx/UPSTREAM_SYNC.md --
# read that document for the "why" behind each step. This script only
# implements the "how": every step is echoed as it runs, any unexpected
# condition aborts loudly instead of guessing, and nothing is ever pushed
# without --push.
#
# Usage: scripts/gx/sync-upstream.sh [--dry-run] [--push]
#
#   --dry-run   Fast-forward `main` to `upstream/main` and stop there --
#               before touching `gx/main` at all. Useful to see whether
#               upstream moved (and whether it force-pushed) without
#               committing to a rebase.
#   --push      Actually push gx/main at the end, with --force-with-lease.
#               Without this flag the script stops after the range-diff
#               check and leaves the push to you.
#
# Requires: the `upstream` remote already points at xai-org/grok-build, and
# the working tree is on (or can check out) `main` and `gx/main`.

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
repo_root="$(cd -- "${script_dir}/../.." >/dev/null 2>&1 && pwd -P)"

dry_run=false
do_push=false

usage() {
    cat <<'EOF'
Usage: scripts/gx/sync-upstream.sh [--dry-run] [--push]

  --dry-run   Stop after fast-forwarding main to upstream/main, before
              rebasing gx/main.
  --push      Push gx/main with --force-with-lease at the end. Omit to stop
              short of pushing.
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)
            dry_run=true
            shift
            ;;
        --push)
            do_push=true
            shift
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        *)
            echo "sync-upstream.sh: unknown argument: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

step() {
    echo "==> $*" >&2
}

die() {
    echo "sync-upstream.sh: $*" >&2
    exit 1
}

cd -- "${repo_root}"

step "1/13 Refusing a dirty worktree"
dirty="$(git status --porcelain)"
if [[ -n "${dirty}" ]]; then
    echo "${dirty}" >&2
    die "worktree is dirty (see above); commit, stash, or discard before syncing"
fi
echo "  clean"

step "2/13 Recording old refs"
if ! git rev-parse --verify --quiet upstream/main >/dev/null; then
    die "upstream/main not found; add the remote first: git remote add upstream https://github.com/xai-org/grok-build.git"
fi
if ! git rev-parse --verify --quiet gx/main >/dev/null; then
    die "gx/main not found locally"
fi
upstream_old="$(git rev-parse upstream/main)"
gx_old="$(git rev-parse gx/main)"
echo "  upstream_old=${upstream_old}"
echo "  gx_old=${gx_old}"

step "3/13 Fetching upstream"
git fetch upstream

step "4/13 Verifying upstream did not rewrite history"
if ! git merge-base --is-ancestor "${upstream_old}" upstream/main; then
    die "upstream/main was rewritten (force-pushed) since upstream_old=${upstream_old}; \
refusing to rebase automatically. Fall back to the manual path in \
docs/gx/UPSTREAM_SYNC.md: format-patch the gx series onto the new snapshot \
and apply it by hand."
fi
echo "  upstream_old is still an ancestor of upstream/main"

step "5/13 Creating a backup ref"
backup_ref="gx/backup/$(date +%F)"
if git rev-parse --verify --quiet "${backup_ref}" >/dev/null; then
    echo "  ${backup_ref} already exists; leaving it as-is"
else
    git branch "${backup_ref}" gx/main
    echo "  created ${backup_ref} at ${gx_old}"
fi

step "6/13 Enabling git rerere"
git config rerere.enabled true

step "7/13 Fast-forwarding main to upstream/main"
git checkout main
if ! git merge --ff-only upstream/main; then
    die "main did not fast-forward to upstream/main; this should not happen after step 4 passed"
fi
echo "  main is now at $(git rev-parse main)"

if [[ "${dry_run}" == true ]]; then
    step "--dry-run: stopping before the gx/main rebase"
    exit 0
fi

step "8/13 Rebasing gx/main onto main"
git checkout gx/main
if ! git rebase main; then
    echo "sync-upstream.sh: rebase produced conflicts." >&2
    echo "  Aborting rather than resolving blind (see docs/gx/UPSTREAM_SYNC.md step 9)." >&2
    git rebase --abort || true
    die "rebase aborted; resolve by hand, or fall back to the format-patch path"
fi
echo "  rebase applied cleanly"

step "9/13 Unexpected-conflict guard: n/a (rebase already applied cleanly, or the script aborted above)"

step "10/13 Cargo.lock reminder"
echo "  Cargo.lock is never blind-regenerated by this script. If a later step" >&2
echo "  reports a concrete cargo error naming it, resolve that manually and" >&2
echo "  review the diff before committing." >&2

step "11/13 Gate: targeted tests (CI parity, all --locked)"
cargo check -p xai-grok-pager-bin --locked
cargo test -p xai-grok-sampling-types --locked
cargo test -p xai-grok-config --locked
cargo test -p xai-grok-pager --lib --locked
cargo test -p xai-grok-update --locked
cargo test -p xai-grok-version --locked
cargo test -p xai-grok-shell --lib --locked -- leader:: agent::model_providers::tests:: session_compact
cargo test -p xai-grok-shell --locked --test test_sampling_client
cargo test -p xai-grok-shell --locked --bin chat-history-downgrade
echo "  gate passed"

step "12/13 Range-diff sanity check"
echo "  Expect only patch-movement noise below -- a content-level diff means" >&2
echo "  go re-read that commit before pushing." >&2
git range-diff "${upstream_old}..${gx_old}" upstream/main..gx/main || true

step "13/13 Push"
if [[ "${do_push}" == true ]]; then
    git push --force-with-lease origin gx/main
    echo "  pushed gx/main"
else
    echo "  --push not given; not pushing. Review the range-diff above, then run:"
    echo "    git push --force-with-lease origin gx/main"
fi

step "Done. gx/main is now at $(git rev-parse gx/main)."
if [[ "${do_push}" != true ]]; then
    echo "Reminder: any local branch based on the old gx/main ($gx_old) needs:" >&2
    echo "  git rebase --onto gx/main ${gx_old} <branch>" >&2
fi
